INSERT INTO diseases (name, description, type) VALUES
('Cảm cúm', 'Bệnh do virus gây ra, thường gặp trong mùa đông và xuân.', 'acute'),
('Viêm phổi', 'Viêm phổi có thể do vi khuẩn, virus, hoặc nấm gây ra.', 'acute'),
('Tiểu đường', 'Là bệnh mãn tính ảnh hưởng đến cách cơ thể chuyển hóa thức ăn thành năng lượng.', 'chronic'),
('Tăng huyết áp', 'Tăng huyết áp là tình trạng huyết áp cao vượt mức bình thường.', 'chronic'),
('Viêm gan B', 'Viêm gan B là bệnh do virus Hepatitis B gây ra.', 'chronic'),
('Viêm gan C', 'Viêm gan C gây tổn thương gan do virus Hepatitis C.', 'chronic'),
('Bệnh tim mạch', 'Các bệnh liên quan đến tim và mạch máu.', 'chronic'),
('Ung thư phổi', 'Là bệnh ung thư xảy ra trong phổi, một trong những loại ung thư phổ biến nhất.', 'chronic'),
('Ung thư gan', 'Ung thư gan thường gặp ở những người có tiền sử viêm gan B hoặc C.', 'chronic'),
('HIV/AIDS', 'Là bệnh do virus HIV gây suy giảm miễn dịch trong cơ thể.', 'chronic'),
('Sốt rét', 'Bệnh truyền nhiễm do ký sinh trùng Plasmodium gây ra.', 'acute'),
('Bệnh dại', 'Bệnh lây qua vết cắn của động vật nhiễm virus dại.', 'acute'),
('Bệnh lao', 'Bệnh do vi khuẩn Mycobacterium tuberculosis gây ra.', 'chronic'),
('Sởi', 'Bệnh do virus gây ra với triệu chứng sốt, phát ban đỏ và ho.', 'acute'),
('Thủy đậu', 'Bệnh do virus Varicella zoster gây ra, gây ra mụn nước trên da.', 'acute'),
('Viêm amidan', 'Viêm nhiễm ở amidan gây đau họng và khó nuốt.', 'acute'),
('Bệnh đái tháo đường type 2', 'Bệnh liên quan đến việc cơ thể không thể sử dụng insulin hiệu quả.', 'chronic'),
('Viêm khớp', 'Viêm khớp gây đau nhức và sưng khớp.', 'chronic'),
('Loãng xương', 'Là tình trạng mất mật độ xương, làm cho xương dễ gãy.', 'chronic'),
('Viêm loét dạ dày', 'Bệnh viêm và loét niêm mạc dạ dày.', 'chronic'),
('Bệnh Parkinson', 'Là bệnh về thần kinh khiến cho bệnh nhân gặp khó khăn trong việc vận động.', 'chronic'),
('Bệnh Alzheimer', 'Một dạng bệnh suy giảm trí nhớ nghiêm trọng, thường gặp ở người cao tuổi.', 'chronic'),
('Hen suyễn', 'Bệnh về phổi gây khó thở, ho và thở khò khè.', 'chronic'),
('Viêm mũi dị ứng', 'Bệnh dị ứng với phấn hoa, bụi bẩn, hoặc lông động vật.', 'chronic'),
('Suy thận', 'Là tình trạng thận không còn khả năng lọc chất thải hiệu quả.', 'chronic'),
('Bệnh gout', 'Bệnh viêm khớp do tích tụ axit uric trong cơ thể.', 'chronic'),
('Cao huyết áp', 'Tình trạng huyết áp tăng cao, gây ra các vấn đề về tim và mạch máu.', 'chronic'),
('Tổn thương tủy sống', 'Chấn thương làm hỏng tủy sống, ảnh hưởng đến các chức năng vận động và cảm giác.', 'acute'),
('Viêm ruột thừa', 'Là tình trạng viêm nhiễm của ruột thừa.', 'acute'),
('Viêm dạ dày', 'Viêm dạ dày có thể do vi khuẩn hoặc thuốc gây ra.', 'acute'),
('Bệnh Crohn', 'Là bệnh viêm nhiễm mạn tính của đường tiêu hóa.', 'chronic'),
('Bệnh tiêu chảy', 'Tiêu chảy là tình trạng đi ngoài nhiều lần, phân lỏng.', 'acute'),
('Rối loạn tiêu hóa', 'Bệnh lý ảnh hưởng đến quá trình tiêu hóa thức ăn trong cơ thể.', 'chronic'),
('Chảy máu cam', 'Là hiện tượng chảy máu từ mũi, thường do khô hoặc viêm nhiễm.', 'acute'),
('Bệnh u não', 'U não có thể là khối u lành tính hoặc ác tính.', 'chronic'),
('Bệnh xơ gan', 'Là tình trạng tổn thương gan nghiêm trọng do viêm gan mạn tính.', 'chronic'),
('Rối loạn lipid máu', 'Là tình trạng mỡ trong máu cao, làm tăng nguy cơ bệnh tim mạch.', 'chronic'),
('Suy tim', 'Là tình trạng tim không thể bơm đủ máu cho cơ thể.', 'chronic'),
('Bệnh động kinh', 'Bệnh gây ra các cơn co giật do sự bất thường của điện não.', 'chronic'),
('Bệnh rối loạn thần kinh', 'Các rối loạn ảnh hưởng đến hệ thần kinh trung ương và ngoại biên.', 'chronic'),
('Bệnh viêm gan A', 'Bệnh viêm gan do virus Hepatitis A gây ra.', 'acute'),
('Bệnh suy hô hấp', 'Là tình trạng suy giảm chức năng hô hấp, ảnh hưởng đến việc trao đổi oxy.', 'chronic'),
('Mù lòa', 'Bệnh mất khả năng nhìn do tổn thương mắt hoặc các bệnh lý liên quan.', 'chronic'),
('Bệnh suy gan', 'Là tình trạng gan mất khả năng chức năng, dẫn đến các vấn đề sức khỏe nghiêm trọng.', 'chronic'),
('Bệnh nhân mạch vành', 'Là tình trạng bệnh lý liên quan đến các động mạch vành của tim.', 'chronic'),
('Bệnh viêm khớp dạng thấp', 'Bệnh viêm khớp tự miễn gây đau nhức và sưng khớp.', 'chronic'),
('Bệnh rối loạn ăn uống', 'Các rối loạn liên quan đến thói quen ăn uống và hành vi liên quan.', 'chronic'),
('Trầm cảm', 'Bệnh lý về tâm thần gây cảm giác buồn bã, mất hứng thú với cuộc sống.', 'chronic'),
('Lo âu', 'Là trạng thái lo lắng quá mức về các sự kiện trong cuộc sống.', 'chronic'),
('Suy giảm miễn dịch', 'Là tình trạng hệ thống miễn dịch không hoạt động hiệu quả, làm cơ thể dễ bị nhiễm trùng.', 'chronic'),
('Bệnh vẩy nến', 'Bệnh về da gây ra các mảng vẩy trắng hoặc đỏ.', 'chronic'),
('Cúm mùa', 'Là bệnh cúm xuất hiện vào mùa đông, gây ra các triệu chứng cảm lạnh.', 'acute');
