INSERT INTO medicines (id, name, description, indications, unit) VALUES
(1, 'Paracetamol', 'Giảm đau, hạ sốt', 'Sốt, đau đầu, cảm cúm', 'Viên'),
(2, 'Ibuprofen', 'Giảm đau, chống viêm', 'Đau nhức, viêm khớp, sốt', 'Viên'),
(3, 'Amoxicillin', 'Kháng sinh nhóm Penicillin', 'Nhiễm trùng hô hấp, tiết niệu', 'Viên'),
(4, 'Cefixime', 'Kháng sinh Cephalosporin', 'Nhiễm khuẩn hô hấp, tiêu hóa', 'Viên'),
(5, 'Metformin', 'Thuốc kiểm soát đường huyết', 'Tiểu đường type 2', 'Viên'),
(6, 'Gliclazide', 'Thuốc hạ đường huyết', 'Tiểu đường type 2', 'Viên'),
(7, 'Aspirin', 'Giảm đau, chống đông máu', 'Đau đầu, nhồi máu cơ tim, đột quỵ', 'Viên'),
(8, 'Loratadine', 'Thuốc kháng histamin', 'Dị ứng, viêm mũi dị ứng', 'Viên'),
(9, 'Cetirizine', 'Kháng histamin thế hệ 2', 'Dị ứng, mề đay, viêm mũi dị ứng', 'Viên'),
(10, 'Fexofenadine', 'Kháng histamin không gây buồn ngủ', 'Dị ứng, mẩn ngứa', 'Viên'),
(11, 'Ranitidine', 'Giảm tiết axit dạ dày', 'Viêm loét dạ dày, trào ngược dạ dày', 'Viên'),
(12, 'Omeprazole', 'Ức chế bơm proton', 'Trào ngược dạ dày, viêm loét dạ dày', 'Viên'),
(13, 'Esomeprazole', 'Thuốc giảm axit dạ dày', 'Trào ngược dạ dày, viêm loét dạ dày', 'Viên'),
(14, 'Simvastatin', 'Hạ cholesterol', 'Mỡ máu cao, phòng bệnh tim mạch', 'Viên'),
(15, 'Atorvastatin', 'Thuốc hạ lipid máu', 'Mỡ máu cao, xơ vữa động mạch', 'Viên'),
(16, 'Rosuvastatin', 'Thuốc giảm cholesterol', 'Mỡ máu cao, phòng bệnh tim', 'Viên'),
(17, 'Losartan', 'Thuốc hạ huyết áp nhóm ARB', 'Tăng huyết áp, suy tim', 'Viên'),
(18, 'Amlodipine', 'Chẹn kênh canxi', 'Tăng huyết áp, đau thắt ngực', 'Viên'),
(19, 'Nifedipine', 'Hạ huyết áp, giãn mạch', 'Tăng huyết áp, đau thắt ngực', 'Viên'),
(20, 'Furosemide', 'Thuốc lợi tiểu quai', 'Tăng huyết áp, suy tim, phù nề', 'Viên'),
(21, 'Hydrochlorothiazide', 'Thuốc lợi tiểu thiazide', 'Tăng huyết áp, phù nề', 'Viên'),
(22, 'Spironolactone', 'Thuốc lợi tiểu giữ kali', 'Suy tim, tăng huyết áp', 'Viên'),
(23, 'Dexamethasone', 'Corticosteroid chống viêm', 'Viêm khớp, dị ứng, suy thượng thận', 'Viên'),
(24, 'Prednisolone', 'Corticosteroid chống viêm', 'Viêm da, hen suyễn, bệnh tự miễn', 'Viên'),
(25, 'Methylprednisolone', 'Corticosteroid mạnh', 'Viêm khớp, bệnh tự miễn', 'Viên'),
(26, 'Budesonide', 'Corticosteroid đường hô hấp', 'Hen suyễn, viêm mũi dị ứng', 'Xịt'),
(27, 'Salbutamol', 'Giãn phế quản', 'Hen suyễn, COPD', 'Xịt'),
(28, 'Ipratropium', 'Giãn phế quản', 'Bệnh phổi tắc nghẽn mãn tính (COPD)', 'Xịt'),
(29, 'Tiotropium', 'Giãn phế quản dài hạn', 'COPD', 'Xịt'),
(30, 'Theophylline', 'Dãn phế quản', 'Hen suyễn, COPD', 'Viên'),
(31, 'Acetylcysteine', 'Long đờm', 'Viêm phế quản, bệnh phổi', 'Viên'),
(32, 'Ambroxol', 'Long đờm', 'Ho có đờm, viêm phế quản', 'Viên'),
(33, 'Carbocisteine', 'Long đờm', 'Bệnh phổi mạn tính, ho đờm', 'Viên'),
(34, 'Erythromycin', 'Kháng sinh Macrolide', 'Nhiễm khuẩn đường hô hấp, da', 'Viên'),
(35, 'Clarithromycin', 'Kháng sinh Macrolide', 'Nhiễm khuẩn đường hô hấp, tiêu hóa', 'Viên'),
(36, 'Azithromycin', 'Kháng sinh Macrolide', 'Viêm phổi, nhiễm trùng da', 'Viên'),
(37, 'Doxycycline', 'Kháng sinh Tetracycline', 'Nhiễm khuẩn da, hô hấp', 'Viên'),
(38, 'Ciprofloxacin', 'Kháng sinh Fluoroquinolone', 'Nhiễm khuẩn nặng', 'Viên'),
(39, 'Levofloxacin', 'Kháng sinh Fluoroquinolone', 'Viêm phổi, nhiễm khuẩn da', 'Viên'),
(40, 'Moxifloxacin', 'Kháng sinh Fluoroquinolone', 'Viêm phổi, nhiễm khuẩn nặng', 'Viên'),
(41, 'Fluconazole', 'Thuốc kháng nấm', 'Nhiễm nấm Candida', 'Viên'),
(42, 'Ketoconazole', 'Thuốc kháng nấm', 'Nấm da, gàu', 'Viên'),
(43, 'Itraconazole', 'Thuốc kháng nấm', 'Nhiễm nấm hệ thống', 'Viên'),
(44, 'Rifampicin', 'Kháng sinh chống lao', 'Lao phổi, lao màng não', 'Viên'),
(45, 'Isoniazid', 'Kháng sinh chống lao', 'Lao phổi, lao ngoài phổi', 'Viên'),
(46, 'Pyrazinamide', 'Thuốc chống lao', 'Lao phổi', 'Viên'),
(47, 'Ethambutol', 'Thuốc chống lao', 'Lao phổi', 'Viên'),
(48, 'Oseltamivir', 'Thuốc kháng virus', 'Cúm A, Cúm B', 'Viên'),
(49, 'Favipiravir', 'Thuốc kháng virus', 'COVID-19', 'Viên'),
(50, 'Remdesivir', 'Thuốc kháng virus', 'COVID-19', 'Tiêm'),
(51, 'Naproxen', 'Giảm đau, chống viêm', 'Đau cơ, viêm khớp', 'Viên'),
(52, 'Tramadol', 'Giảm đau', 'Đau nặng, sau phẫu thuật', 'Viên'),
(53, 'Codeine', 'Giảm đau, ho', 'Ho, đau nhẹ đến vừa', 'Viên'),
(54, 'Bromhexine', 'Long đờm', 'Viêm phế quản, ho có đờm', 'Viên'),
(55, 'Guaifenesin', 'Long đờm', 'Ho có đờm', 'Viên'),
(56, 'Loperamide', 'Chống tiêu chảy', 'Tiêu chảy cấp, mãn tính', 'Viên'),
(57, 'Metoclopramide', 'Chống nôn', 'Buồn nôn, nôn', 'Viên'),
(58, 'Domperidone', 'Chống nôn', 'Buồn nôn, nôn', 'Viên'),
(59, 'Ondansetron', 'Chống nôn', 'Nôn sau hóa trị', 'Viên'),
(60, 'Folic acid', 'Bổ sung vitamin', 'Thiếu máu, mang thai', 'Viên'),
(61, 'Vitamin C', 'Bổ sung vitamin', 'Thiếu vitamin C', 'Viên'),
(62, 'Calcium carbonate', 'Bổ sung canxi', 'Loãng xương, thiếu canxi', 'Viên'),
(63, 'Iron sulfate', 'Bổ sung sắt', 'Thiếu máu thiếu sắt', 'Viên'),
(64, 'Magnesium sulfate', 'Bổ sung magiê', 'Thiếu magiê', 'Viên'),
(65, 'Potassium chloride', 'Bổ sung kali', 'Thiếu kali', 'Viên');
