export {default as PatientMainLayout} from "./patientLayout/PatientMainLayout"
export {default as AuthLayout} from "./authLayout/AuthLayout"
export { default as FacilityLayout } from "./FacilityLayout/FacilityLayout"
export { default as DoctorLayout } from "./DoctorLayout/DoctorLayout"
export { default as AdminLayout } from "./adminLayout/AdminLayout"
