INSERT INTO allergies (name, description) VALUES
('Dị ứng phấn hoa', 'Phản ứng dị ứng với phấn hoa từ cây, cỏ và hoa.'),
('Dị ứng lông động vật', 'Phản ứng dị ứng với lông mèo, chó và động vật khác.'),
('Dị ứng bụi nhà', 'Phản ứng dị ứng với bọ bụi nhà và các hạt nhỏ trong bụi.'),
('Dị ứng đậu phộng', 'Phản ứng dị ứng với đậu phộng, có thể gây sốc phản vệ.'),
('Dị ứng hải sản', 'Phản ứng dị ứng với tôm, cua, sò, và các loại hải sản khác.'),
('Dị ứng sữa', 'Phản ứng dị ứng với protein trong sữa bò.'),
('Dị ứng trứng', 'Phản ứng dị ứng với lòng trắng hoặc lòng đỏ trứng.'),
('Dị ứng đậu nành', 'Phản ứng dị ứng với protein trong đậu nành.'),
('Dị ứng lúa mì', 'Phản ứng dị ứng với gluten trong lúa mì.'),
('Dị ứng hạt cây', 'Phản ứng dị ứng với hạnh nhân, óc chó, hạt điều, v.v.'),
('Dị ứng cá', 'Phản ứng dị ứng với cá hồi, cá ngừ và các loại cá khác.'),
('Dị ứng penicillin', 'Phản ứng dị ứng với thuốc kháng sinh nhóm penicillin.'),
('Dị ứng aspirin', 'Phản ứng dị ứng với thuốc aspirin và NSAIDs khác.'),
('Dị ứng sulfa', 'Phản ứng dị ứng với thuốc chứa sulfa.'),
('Dị ứng insulin', 'Phản ứng dị ứng với insulin dùng để điều trị tiểu đường.'),
('Dị ứng thuốc gây mê', 'Phản ứng dị ứng với thuốc gây mê khi phẫu thuật.'),
('Dị ứng ong', 'Phản ứng dị ứng với nọc độc của ong.'),
('Dị ứng kiến lửa', 'Phản ứng dị ứng với vết cắn của kiến lửa.'),
('Dị ứng muỗi', 'Phản ứng dị ứng với vết đốt của muỗi.'),
('Dị ứng nước hoa', 'Phản ứng dị ứng với hương liệu trong nước hoa.'),
('Dị ứng mỹ phẩm', 'Phản ứng dị ứng với các thành phần trong mỹ phẩm.'),
('Dị ứng xà phòng', 'Phản ứng dị ứng với các hóa chất trong xà phòng và chất tẩy rửa.'),
('Dị ứng thuốc nhuộm tóc', 'Phản ứng dị ứng với các thành phần trong thuốc nhuộm tóc.'),
('Dị ứng cao su latex', 'Phản ứng dị ứng với protein trong cao su latex.'),
('Dị ứng lạnh', 'Phản ứng dị ứng khi tiếp xúc với thời tiết lạnh.'),
('Dị ứng nóng', 'Phản ứng dị ứng khi tiếp xúc với nhiệt độ cao.'),
('Dị ứng ánh nắng', 'Phản ứng dị ứng với tia UV từ ánh nắng mặt trời.'),
('Dị ứng độ ẩm', 'Phản ứng dị ứng khi độ ẩm trong không khí cao.'),
('Dị ứng kim loại', 'Phản ứng dị ứng với nickel, bạc hoặc các kim loại khác trong trang sức.');
